# Default values for anzograph.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# Values for statefulset
CsiAnzograph:
  Image: "docker.io/cambridgesemantics/anzograph:latest"
  ImagePullPolicy: "IfNotPresent"
  Resources:
    Cpu: "4000m"
    Memory: "8000Mi"

# Anzograph UI credentials
AnzographUICredentials:
  UIAdminUser: "admin"
  UIAdminPassword: "Passw0rd1"
  QUERYUser: "query"
  QUERYUserPassword: "Passw0rd2"
  
# UI frontend LB service 
# The target ports are non-editable
AnzographUIService:
  Ports:
   Jetty_Https:
     Port: 443
     TargetPort: 8443
   Jetty_Http:
     Port: 80
     TargetPort: 8080

# Anzograph configmap variables to specify existing certs with path 
User_Certs: false
AnzographConfigmap:
  user_cert_path: {}
  user_key_path: {}
  user_ca_cert_path: {}
