apiVersion: v1
kind: ConfigMap
metadata:
  name: anzograph-configmap
  labels:
    app: "{{ .Chart.Name }}"
data:

{{- if .Values.User_Certs  }}
  user.cert: |-
{{ .Files.Get "{{ .Values.AnzographConfigmap.user_cert_path }}" | indent 4 }}

  user.key: |-
{{ .Files.Get "{{ .Values.AnzographConfigmap.user_key_path }}" | indent 4 }}

  user_ca.cert: |-
{{ .Files.Get "{{ .Values.AnzographConfigmap.user_ca_cert_path }}" | indent 4 }}
{{- end }}
