apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-ui"
  labels:
    app: "{{ .Release.Name }}"
spec:
  ports:
  - port: {{ .Values.AnzographUIService.Ports.Jetty_Https.Port }}
    targetPort: 8443
    name: https
  - port: {{ .Values.AnzographUIService.Ports.Jetty_Http.Port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: "{{ .Release.Name }}"
  type: LoadBalancer
