---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Chart.Name }}-leader"
spec:
  serviceName: "{{ .Chart.Name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        component: "{{ .Chart.Name }}-leader"
    spec:
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.CsiAnzograph.Image }}"
        imagePullPolicy: "{{ .Values.CsiAnzograph.ImagePullPolicy }}"
        resources:
          requests:
            cpu: "{{ .Values.CsiAnzograph.Resources.Cpu }}"
            memory: "{{ .Values.CsiAnzograph.Resources.Memory }}"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - name: jetty-credentials
          mountPath: /jetty-credentials
      volumes:
      - name: jetty-credentials
        secret:
          secretName: "{{ .Release.Name }}-ui-secrets"
      terminationGracePeriodSeconds: 30
