apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-ui-secrets"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: kubernetes.io/storageos
data:
  UIAdminUser: {{ default "" .Values.AnzographUICredentials.UIAdminUser | b64enc | quote }}
  UIAdminPassword: {{ default "" .Values.AnzographUICredentials.UIAdminPassword | b64enc | quote }}
  QUERYUser: {{ default "" .Values.AnzographUICredentials.QUERYUser | b64enc | quote }}
  QUERYUserPassword: {{ default "" .Values.AnzographUICredentials.QUERYUserPassword | b64enc | quote }}
